Media versioning
Islandora/Crayfish pull request #96
Opened 2020-02-21 04:35 UTC by elizoller

**GitHub Issue**: (https://github.com/Islandora/documentation/issues/740)

* Other Relevant Links 
https://github.com/Islandora/Alpaca/pull/70

# What does this Pull Request do?
Allows Milliner to fire requests to Fedora to create versions of Media objects

# What's new?
* Separates the routes for node versioning and media versioning - because they rely on different data
* Abstracts shared code with the saveMedia method where possible to reduce duplication
* Creates a Fedora version for a Media object

# How should this be tested?
* Bring in the related Alpaca PR here: https://github.com/Islandora/Alpaca/pull/70
* Clone/pull this PR into Milliner (in playbook - `/var/www/html/Crayfish/Milliner`)
* Create a repository item node (make sure it persists to Fedora)
* Edit the node - make sure it gets a version in Fedora - in Fedora UI or via API call
* Create a media object (make sure it persists to Fedora)
* Edit that media object - make sure it gets a version in Fedora (not available through Fedora UI, have to call like http://127.0.0.1:8080/fcrepo/rest/2020-02/file.pdf/fcr:metadata/fcr:versions

# Interested parties
@Islandora/8-x-committers

2020-09-08 20:27 UTC, dannylamb requested changes
Other than some small things, this looks like a good little refactor.  We'll have to sort out what's up with tests, too, but I'm :+1: to this.

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Controller/MillinerController.php
> +            $this->log->info("in create Node version with " . $uuid);
I would delete this or set the level to debug.

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Controller/MillinerController.php
> +            $this->log->info($urls);
I would delete these two lines or set the levels to debug.

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Controller/MillinerController.php
> +            $this->log->info("json url is EMPTY");
I would use error instead of info here

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Controller/MillinerController.php
> +            $this->log->info("json url is" . $json_url);
I'd make this debug or delete it

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Service/MillinerService.php
> +        $this->log->error("the fedora url in service is " . $fedora_url);
I'd make this debug or delete it.

2020-09-08 20:27 UTC, dannylamb commented on Milliner/src/Service/MillinerService.php
> +        return array('fedora'=>$urls['fedora'], 'jsonld' =>$jsonld_url, 'drupal'=>$urls['drupal']);
I hate myself for nitpicking on this, but you should use `[]` instead of `array` here

2020-09-08 20:34 UTC, dannylamb commented
Hrm... Chullo _is_ out of date at 30f13e7 according to the composer install output from Travis, but it is recent enough to contain versioning.  It's not a bad idea to run `composer update` and commit the updated lockfile just in case.

2020-09-09 17:46 UTC, elizoller commented
I might need some help with the tests here: https://travis-ci.com/github/Islandora/Crayfish/jobs/382853022

2020-09-10 18:30 UTC, dannylamb commented
Because you refactored and added the `getGeminiUrls` and `getFileFromMedia` functions, you need to wire up  your mocks to return values for them or throw exceptions.  Here's a diff of what I had to do to get them working.

```diff
diff --git a/Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php b/Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php
index 09b9e74..e28e5f9 100644
--- a/Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php
+++ b/Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php
@@ -48,12 +48,16 @@ class MillinerControllerTest extends TestCase
         $milliner = $this->prophesize(MillinerServiceInterface::class);
         $milliner->saveNode(Argument::any(), Argument::any(), Argument::any(), Argument::any())
             ->willThrow(new \Exception("Forbidden", 403));
+        $milliner->getFileFromMedia(Argument::any(), Argument::any(), Argument::any())
+            ->willThrow(new \Exception("Forbidden", 403));
         $milliner->saveMedia(Argument::any(), Argument::any(), Argument::any())
             ->willThrow(new \Exception("Forbidden", 403));
         $milliner->deleteNode(Argument::any(), Argument::any())
             ->willThrow(new \Exception("Forbidden", 403));
         $milliner->saveExternal(Argument::any(), Argument::any(), Argument::any(), Argument::any())
             ->willThrow(new \Exception("Forbidden", 403));
+        $milliner->getGeminiUrls(Argument::any(), Argument::any())
+            ->willThrow(new \Exception("Forbidden", 403));
         $milliner->createVersion(Argument::any(), Argument::any())
             ->willThrow(new \Exception("Forbidden", 403));
         $milliner = $milliner->reveal();
@@ -473,7 +477,9 @@ class MillinerControllerTest extends TestCase
     public function testCreateNodeVersionReturnsSuccessOnSuccess()
     {
         $milliner = $this->prophesize(MillinerServiceInterface::class);
-        $milliner->createVersion(Argument::any(), Argument::any(), Argument::any(), Argument::any())
+        $milliner->getGeminiUrls(Argument::any(), Argument::any())
+            ->willReturn(['fedora' => "http://example.org/fcrepo/abc123", "drupal" => "http://example.org/node/1"]);
+        $milliner->createVersion(Argument::any(), Argument::any())
             ->willReturn(new Response(201));
         $milliner = $milliner->reveal();
         $controller = new MillinerController($milliner, $this->logger);
@@ -499,7 +505,9 @@ class MillinerControllerTest extends TestCase
         );
 
         $milliner = $this->prophesize(MillinerServiceInterface::class);
-        $milliner->createVersion(Argument::any(), Argument::any(), Argument::any(), Argument::any())
+        $milliner->getGeminiUrls(Argument::any(), Argument::any())
+            ->willReturn(['fedora' => "http://example.org/fcrepo/abc123", "drupal" => "http://example.org/node/1"]);
+        $milliner->createVersion(Argument::any(), Argument::any())
             ->willReturn(new Response(204));
         $milliner = $milliner->reveal();
         $controller = new MillinerController($milliner, $this->logger);
```

2020-09-10 19:29 UTC, elizoller commented
my hero!!!

2020-09-11 12:32 UTC, dannylamb approved these changes

2020-09-11 12:53 UTC, merged